name: Deploy to Firebase on Push
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUELDOFACIL_WEB_APP }}'
      
      - uses: 'google-github-actions/setup-gcloud@v2'
        
      - name: 'Deploy to Firebase'
        run: |-
          # Prepara el entorno de Python
          pip install -r functions/requirements.txt
          
          # El comando de despliegue, ahora ejecutado directamente
          firebase deploy --project sueldofacil-web-app --force
