# Nombre del workflow, aparece en la pestaña "Actions" de GitHub
name: Deploy Full App to Firebase

# Se ejecuta automáticamente cada vez que subes cambios a la rama 'main'
'on':
  push:
    branches:
      - main

# Define los trabajos que se van a ejecutar
jobs:
  build_and_deploy:
    # Se ejecuta en un servidor Linux estándar de GitHub
    runs-on: ubuntu-latest
    
    # Define los pasos del trabajo
    steps:
      # 1. Descarga tu código del repositorio a la máquina virtual
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Configura el entorno de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Instala las dependencias de Python que están en tu requirements.txt
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f functions/requirements.txt ]; then pip install -r functions/requirements.txt; fi

      # 4. El paso final que despliega TODO a Firebase
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUELDOFACIL_WEB_APP }}'
          projectId: sueldofacil-web-app
          channelId: live
          target: sueldofacil-web-app