name: Deploy to Firebase on Push
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SUELDOFACIL_WEB_APP }}'
      
      - uses: 'google-github-actions/setup-gcloud@v2'
        
      - name: 'Install Firebase Tools and Deploy'
        run: |-
          # PASO 1: Instalar firebase-tools
          npm install -g firebase-tools

          # PASO 2: Instalar dependencias de Python
          pip install -r functions/requirements.txt
          
          # PASO 3: Desplegar
          firebase deploy --project sueldofacil-web-app --force
